config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :comments, only: [:create]
  end
  resources :users, except: [ :index  ]
  resources :categories, only: %i[new create show index]
  get 'logout', to: 'sessions#destroy'
  get 'login', to: 'sessions#new'
  get '/articles/:article_id/vote', to: 'votes#create', as: 'vote'
  get '/articles/:article_id/unvote', to: 'votes#destroy', as: 'unvote'
  get 'users/:id/delete', to: 'users#destroy', as: 'delete_user'
  post 'login', to: 'sessions#create'
  root to: 'articles#index'
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  has_many :articles, foreign_key: 'author_id', dependent: :destroy
  has_many :votes, foreign_key: 'user_id', dependent: :destroy
  has_many :comments, foreign_key: 'user_id', dependent: :destroy
  has_one_attached :profile_image, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :logged?, only: %i[edit update destroy]
  before_action :user?, only: %i[edit update destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:current_user] = @user
      flash[:notice] = 'You have successfully logged in.'
      redirect_to root_path
    else
      flash.now[:notice] = @user.errors.full_messages
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @user.id == session['current_user']['id']
      reset_session
      session.clear
    end
    @user.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user?
    if @user.id == session['current_user']['id'] || session['current_user']['admin'] == true
      true
    else
      redirect_to root_path, notice: "HaHaHa nice try, Unfortunally you can't edit or destroy another user's account."
    end
  end

  def logged?
    session.key?('current_user') ? true : redirect_to(login_path, notice: 'You have to Login first.')
  end

  def user_params
    params.require(:user).permit(:name, :email, :profile_image)
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
<div class="container-fluid bg-white login-container p-5 ">
    <div class="container form-container  w-lg-50 bg-white p-5 my-5 ">

        <h1 class="text-center  mb-4 "> Signup </h1>
        <div class="form-group">
            <%= form.label :name %>
            <%= form.text_field :name, class: "form-control", :placeholder=> "Choose a username." %>
        </div>

        <div class="form-group">
            <%= form.label :email %>
            <%= form.text_field :email, class: "form-control", :placeholder=> "Enter email." %>
        </div>

        <div class="form-group">
            <%= form.label :profile_picture %>
            <%= form.file_field :profile_image, class: "form-control" %>
        </div>

        <div class="actions text-center mt-4">
            <%= form.submit "Signup" , class: "btn btn-lg btn-info" %>
            or
            <%= link_to  "Login", login_path %>
        </div>
    </div>
</div>
<% end %>

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true) do |form| %>
<div class="container-fluid bg-white login-container p-5 ">
    <div class="container form-container  w-lg-50 bg-white p-5 my-5 ">

        <h1 class="text-center  mb-4 "> Edit User </h1>
        <div class="form-group">
            <%= form.label :name %>
            <%= form.text_field :name, class: "form-control", :placeholder=> "Choose a username." %>
        </div>

        <div class="form-group">
            <%= form.label :email %>
            <%= form.text_field :email, class: "form-control", :placeholder=> "Enter email." %>
        </div>

        <div class="form-group">
            <%= form.label :profile_picture %>
            <%= form.file_field :profile_image, class: "form-control" %>
        </div>

        <div class="actions text-center mt-4">
            <%= form.submit "Update" , class: "btn btn-lg btn-info" %>
        </div>
    </div>
</div>
<% end %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<div class="container-fluid user-container bg-white p-5">
    <div class="container text-center p-5">
        <div class="user-image">
            <% if @user&.profile_image&.attached? %>
            <%= image_tag @user.profile_image  %>
            <% else %>
            <img  src="https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png">
            <% end %>
        </div>
        <div class="username">
            @<%= @user.name.capitalize %>
        </div>
        <div class="user-email">
            <%= @user.email.capitalize %>
        </div>

        <div class="user-buttons">
            <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-warning" if user?(@user.id) || admin? %>
            <%= link_to 'Delete Account', delete_user_path(@user), class: "btn btn-danger", data: { confirm: 'Are you certain you want to delete this account?' } if user?(@user.id) || admin?%>
        </div>
        <% if admin? %>
        <div class="mt-4">
            <%= link_to 'Create a Category', new_category_path , class: "btn btn-info"%>
        </div>
        <% end %>
    </div>
</div>